// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateIcon(arg1) {
  return window['go']['main']['App']['CreateIcon'](arg1);
}

export function InspectImage(arg1) {
  return window['go']['main']['App']['InspectImage'](arg1);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function SelectOutput(arg1) {
  return window['go']['main']['App']['SelectOutput'](arg1);
}
