// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateIcon(arg1:main.CreateIconRequest):Promise<main.CreateIconResponse>;

export function InspectImage(arg1:string):Promise<main.ImageInfo>;

export function Reveal(arg1:string):Promise<void>;

export function SelectImage():Promise<main.ImageInfo>;

export function SelectOutput(arg1:string):Promise<string>;
